export const quizData = [
  {
    word: 'いち',
    kanji: '一',
    answer: 'one',
    wrongAnswers: ['two', 'three', 'five'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'に',
    kanji: '二',
    answer: 'two',
    wrongAnswers: ['four', 'six', 'eight'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'さん',
    kanji: '三',
    answer: 'three',
    wrongAnswers: ['seven', 'nine', 'ten'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'し',
    kanji: '四',
    answer: 'four',
    wrongAnswers: ['one', 'five', 'nine'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'ご',
    kanji: '五',
    answer: 'five',
    wrongAnswers: ['two', 'four', 'six'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'ろく',
    kanji: '六',
    answer: 'six',
    wrongAnswers: ['three', 'seven', 'ten'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'しち',
    kanji: '七',
    answer: 'seven',
    wrongAnswers: ['two', 'four', 'eight'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'はち',
    kanji: '八',
    answer: 'eight',
    wrongAnswers: ['one', 'three', 'nine'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'きゅう',
    kanji: '九',
    answer: 'nine',
    wrongAnswers: ['two', 'four', 'six'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'じゅう',
    kanji: '十',
    answer: 'ten',
    wrongAnswers: ['three', 'six', 'nine'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'ぜろ',
    kanji: '零',
    answer: 'zero',
    wrongAnswers: ['one', 'five', 'ten'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'げつようび',
    kanji: '月曜日',
    answer: 'Monday',
    wrongAnswers: ['Wednesday', 'Tuesday', 'Sunday'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'かようび',
    kanji: '火曜日',
    answer: 'Tuesday',
    wrongAnswers: ['Thursday', 'Saturday', 'Sunday'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'すいようび',
    kanji: '水曜日',
    answer: 'Wednesday',
    wrongAnswers: ['Friday', 'Monday', 'Thursday'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'もくようび',
    kanji: '木曜日',
    answer: 'Thursday',
    wrongAnswers: ['Tuesday', 'Saturday', 'Sunday'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'きんようび',
    kanji: '金曜日',
    answer: 'Friday',
    wrongAnswers: ['Monday', 'Wednesday', 'Sunday'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'どようび',
    kanji: '土曜日',
    answer: 'Saturday',
    wrongAnswers: ['Monday', 'Wednesday', 'Friday'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にちようび',
    kanji: '日曜日',
    answer: 'Sunday',
    wrongAnswers: ['Tuesday', 'Thursday', 'Saturday'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'れいじ',
    kanji: '',
    answer: "0 o'clock",
    wrongAnswers: ["1 o'clock", "3 o'clock", "5 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'いちじ',
    kanji: '',
    answer: "1 o'clock",
    wrongAnswers: ["2 o'clock", "4 o'clock", "6 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にじ',
    kanji: '',
    answer: "2 o'clock",
    wrongAnswers: ["3 o'clock", "5 o'clock", "7 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'さんじ',
    kanji: '',
    answer: "3 o'clock",
    wrongAnswers: ["4 o'clock", "6 o'clock", "8 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'よじ',
    kanji: '',
    answer: "4 o'clock",
    wrongAnswers: ["5 o'clock", "7 o'clock", "9 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'ごじ',
    kanji: '',
    answer: "5 o'clock",
    wrongAnswers: ["6 o'clock", "8 o'clock", "10 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'ろくじ',
    kanji: '',
    answer: "6 o'clock",
    wrongAnswers: ["7 o'clock", "9 o'clock", "11 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'しちじ',
    kanji: '',
    answer: "7 o'clock",
    wrongAnswers: ["8 o'clock", "10 o'clock", "12 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'はちじ',
    kanji: '',
    answer: "8 o'clock",
    wrongAnswers: ["9 o'clock", "11 o'clock", "1 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'くじ',
    kanji: '',
    answer: "9 o'clock",
    wrongAnswers: ["10 o'clock", "12 o'clock", "2 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅうじ',
    kanji: '',
    answer: "10 o'clock",
    wrongAnswers: ["11 o'clock", "1 o'clock", "3 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅういちじ',
    kanji: '',
    answer: "11 o'clock",
    wrongAnswers: ["12 o'clock", "2 o'clock", "4 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅうにじ',
    kanji: '',
    answer: "12 o'clock",
    wrongAnswers: ["1 o'clock", "3 o'clock", "5 o'clock"],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'いっぷん',
    kanji: '一分',
    answer: '1 minute',
    wrongAnswers: ['2 minutes', '5 minutes', '10 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にふん',
    kanji: '二分',
    answer: '2 minutes',
    wrongAnswers: ['3 minutes', '7 minutes', '20 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'さんぷん',
    kanji: '三分',
    answer: '3 minutes',
    wrongAnswers: ['4 minutes', '8 minutes', '30 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'よんふん',
    kanji: '四分',
    answer: '4 minutes',
    wrongAnswers: ['5 minutes', '9 minutes', '40 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'ごふん',
    kanji: '五分',
    answer: '5 minutes',
    wrongAnswers: ['6 minutes', '10 minutes', '50 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'ろっぷん',
    kanji: '六分',
    answer: '6 minutes',
    wrongAnswers: ['7 minutes', '12 minutes', '20 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'ななふん',
    kanji: '七分',
    answer: '7 minutes',
    wrongAnswers: ['8 minutes', '15 minutes', '25 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'はっぷん',
    kanji: '八分',
    answer: '8 minutes',
    wrongAnswers: ['9 minutes', '16 minutes', '24 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'きゅうふん',
    kanji: '九分',
    answer: '9 minutes',
    wrongAnswers: ['10 minutes', '18 minutes', '27 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅっぷん',
    kanji: '十分',
    answer: '10 minutes',
    wrongAnswers: ['11 minutes', '21 minutes', '35 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にじゅっぷん',
    kanji: '二十分',
    answer: '20 minutes',
    wrongAnswers: ['15 minutes', '25 minutes', '45 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'さんじゅっぷん',
    kanji: '三十分',
    answer: '30 minutes',
    wrongAnswers: ['22 minutes', '35 minutes', '48 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'よんじゅっぷん',
    kanji: '四十分',
    answer: '40 minutes',
    wrongAnswers: ['28 minutes', '38 minutes', '42 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'ごじゅっぷん',
    kanji: '五十分',
    answer: '50 minutes',
    wrongAnswers: ['37 minutes', '55 minutes', '60 minutes'],
    topic: 'Date and Time',
    lesson: '0',
  },

  {
    word: 'いちがつ',
    kanji: '一月',
    answer: 'January',
    wrongAnswers: ['February', 'March', 'April'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にがつ',
    kanji: '二月',
    answer: 'February',
    wrongAnswers: ['January', 'March', 'May'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'さんがつ',
    kanji: '三月',
    answer: 'March',
    wrongAnswers: ['April', 'May', 'June'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'しがつ',
    kanji: '四月',
    answer: 'April',
    wrongAnswers: ['May', 'June', 'July'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'ごがつ',
    kanji: '五月',
    answer: 'May',
    wrongAnswers: ['April', 'June', 'July'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'ろくがつ',
    kanji: '六月',
    answer: 'June',
    wrongAnswers: ['May', 'July', 'August'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'しちがつ',
    kanji: '七月',
    answer: 'July',
    wrongAnswers: ['June', 'August', 'September'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'はちがつ',
    kanji: '八月',
    answer: 'August',
    wrongAnswers: ['July', 'September', 'October'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'くがつ',
    kanji: '九月',
    answer: 'September',
    wrongAnswers: ['August', 'October', 'November'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅうがつ',
    kanji: '十月',
    answer: 'October',
    wrongAnswers: ['September', 'November', 'December'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅういちがつ',
    kanji: '十一月',
    answer: 'November',
    wrongAnswers: ['October', 'December', 'January'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅうにがつ',
    kanji: '十二月',
    answer: 'December',
    wrongAnswers: ['November', 'January', 'February'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'ついたち',
    kanji: '一日',
    answer: '1st',
    wrongAnswers: ['2nd', '5th', '10th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'ふつか',
    kanji: '二日',
    answer: '2nd',
    wrongAnswers: ['3rd', '7th', '20th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'みっか',
    kanji: '三日',
    answer: '3rd',
    wrongAnswers: ['4th', '8th', '30th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'よっか',
    kanji: '四日',
    answer: '4th',
    wrongAnswers: ['5th', '10th', '14th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'いつか',
    kanji: '五日',
    answer: '5th',
    wrongAnswers: ['6th', '15th', '25th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'むいか',
    kanji: '六日',
    answer: '6th',
    wrongAnswers: ['7th', '12th', '21st'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'なのか',
    kanji: '七日',
    answer: '7th',
    wrongAnswers: ['8th', '17th', '27th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'ようか',
    kanji: '八日',
    answer: '8th',
    wrongAnswers: ['9th', '18th', '28th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'ここのか',
    kanji: '九日',
    answer: '9th',
    wrongAnswers: ['10th', '19th', '29th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'とおか',
    kanji: '十日',
    answer: '10th',
    wrongAnswers: ['11th', '20th', '31st'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅういちにち',
    kanji: '十一日',
    answer: '11th',
    wrongAnswers: ['12th', '21st', '25th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅうににち',
    kanji: '十二日',
    answer: '12th',
    wrongAnswers: ['13th', '22nd', '30th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅうさんにち',
    kanji: '十三日',
    answer: '13th',
    wrongAnswers: ['14th', '23rd', '31st'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅうよっか',
    kanji: '十四日',
    answer: '14th',
    wrongAnswers: ['15th', '24th', '30th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅうごにち',
    kanji: '十五日',
    answer: '15th',
    wrongAnswers: ['16th', '25th', '31st'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅうろくにち',
    kanji: '十六日',
    answer: '16th',
    wrongAnswers: ['17th', '26th', '30th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅうしちにち',
    kanji: '十七日',
    answer: '17th',
    wrongAnswers: ['18th', '27th', '31st'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅうはちにち',
    kanji: '十八日',
    answer: '18th',
    wrongAnswers: ['19th', '28th', '30th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'じゅうくにち',
    kanji: '十九日',
    answer: '19th',
    wrongAnswers: ['20th', '29th', '31st'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'はつか',
    kanji: '二十日',
    answer: '20th',
    wrongAnswers: ['21st', '30th', '31st'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にじゅういちにち',
    kanji: '二十一日',
    answer: '21st',
    wrongAnswers: ['22nd', '31st', '27th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にじゅうににち',
    kanji: '二十二日',
    answer: '22nd',
    wrongAnswers: ['23rd', '30th', '31st'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にじゅうさんにち',
    kanji: '二十三日',
    answer: '23rd',
    wrongAnswers: ['24th', '25th', '26th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にじゅうよっか',
    kanji: '二十四日',
    answer: '24th',
    wrongAnswers: ['23rd', '25th', '26th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にじゅうごにち',
    kanji: '二十五日',
    answer: '25th',
    wrongAnswers: ['24th', '26th', '27th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にじゅうろくにち',
    kanji: '二十六日',
    answer: '26th',
    wrongAnswers: ['25th', '27th', '28th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にじゅうしちにち',
    kanji: '二十七日',
    answer: '27th',
    wrongAnswers: ['26th', '28th', '29th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にじゅうはちにち',
    kanji: '二十八日',
    answer: '28th',
    wrongAnswers: ['27th', '29th', '30th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'にじゅうくにち',
    kanji: '二十九日',
    answer: '29th',
    wrongAnswers: ['28th', '30th', '31st'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'さんじゅうにち',
    kanji: '三十日',
    answer: '30th',
    wrongAnswers: ['31st', '29th', '28th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'さんじゅういちにち',
    kanji: '三十一日',
    answer: '31st',
    wrongAnswers: ['30th', '29th', '25th'],
    topic: 'Date and Time',
    lesson: '0',
  },
  {
    word: 'だれ（どなた）',
    kanji: '',
    answer: 'who',
    wrongAnswers: ['what', 'where', 'when'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'いつ',
    kanji: '',
    answer: 'when',
    wrongAnswers: ['what', 'where', 'who'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'どこ',
    kanji: '',
    answer: 'where',
    wrongAnswers: ['what', 'who', 'when'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: '－さい',
    kanji: '－歳',
    answer: '－ years old',
    wrongAnswers: ['－height', '－weight', '－grade'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'なんさい（おいくつ）',
    kanji: '何歳',
    answer: 'how old',
    wrongAnswers: ['what age', 'what year', 'how tall'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'がくせい',
    kanji: '学生',
    answer: 'student',
    wrongAnswers: ['teacher', 'doctor', 'bank employee'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'かいしゃいん',
    kanji: '会社員',
    answer: 'company employee',
    wrongAnswers: ['student', 'researcher', 'doctor'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'しゃいん',
    kanji: '社員',
    answer: 'employee of ～ company',
    wrongAnswers: ['teacher', 'doctor', 'bank employee'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'ぎんこういん',
    kanji: '銀行員',
    answer: 'bank employee',
    wrongAnswers: ['student', 'teacher', 'researcher'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'いしゃ',
    kanji: '医者',
    answer: '[medical] doctor',
    wrongAnswers: ['teacher', 'student', 'bank employee'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'けんきゅうしゃ',
    kanji: '研究者',
    answer: 'researcher, scholar',
    wrongAnswers: ['doctor', 'student', 'company employee'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'だいがく',
    kanji: '大学',
    answer: 'university',
    wrongAnswers: ['hospital', 'bank', 'school'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'びょういん',
    kanji: '病院',
    answer: 'hospital',
    wrongAnswers: ['university', 'bank', 'office'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'わたし',
    kanji: '',
    answer: 'I',
    wrongAnswers: ['you', 'he', 'she'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'あなた',
    kanji: '',
    answer: 'you',
    wrongAnswers: ['I', 'he', 'she'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'あの ひと（あの かた）',
    kanji: 'あの 人（あの 方）',
    answer: 'that person, he, she',
    wrongAnswers: ['this person', 'you', 'we'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: '～さん',
    kanji: '',
    answer: 'Mr., Ms.',
    wrongAnswers: ['Atty', 'Dr.', 'Professor'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: '～ちゃん',
    kanji: '',
    answer: "(suffix for a child's name)",
    wrongAnswers: ['～さん', '～くん', '～様'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: '～じん',
    kanji: '～人',
    answer: "(suffix meaning 'a national of')",
    wrongAnswers: ['～さん', '～ちゃん', '～様'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'せんせい',
    kanji: '先生',
    answer: 'teacher, instructor',
    wrongAnswers: ['doctor', 'student', 'engineer'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'きょうし',
    kanji: '教師',
    answer: 'teacher, instructor',
    wrongAnswers: ['professor', 'pupil', 'coach'],
    topic: 'Words',
    lesson: '1 Words',
  },
  {
    word: 'これ',
    kanji: '',
    answer: 'this (thing here)',
    wrongAnswers: [
      'that (thing near the listener)',
      'that (thing over there)',
      'that (thing near the speaker)',
    ],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'それ',
    kanji: '',
    answer: 'that (thing near the listener)',
    wrongAnswers: ['this (thing here)', 'that (thing over there)', 'that (thing near the speaker)'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'あれ',
    kanji: '',
    answer: 'that (thing over there)',
    wrongAnswers: [
      'this (thing here)',
      'that (thing near the listener)',
      'that (thing near the speaker)',
    ],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'この',
    kanji: '',
    answer: 'this ～, this ～ here',
    wrongAnswers: [
      'that ～, that ～ near the listener',
      'that ～, that ～ over there',
      'these ～, these ～ here',
    ],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'その',
    kanji: '',
    answer: 'that ～, that ～ near the listener',
    wrongAnswers: [
      'this ～, this ～ here',
      'that ～, that ～ over there',
      'these ～, these ～ here',
    ],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'あの',
    kanji: '',
    answer: 'that ～, that ～ over there',
    wrongAnswers: [
      'this ～, this ～ here',
      'that ～, that ～ near the listener',
      'these ～, these ～ here',
    ],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'ほん',
    kanji: '本',
    answer: 'book',
    wrongAnswers: ['dictionary', 'magazine', 'newspaper'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'じしょ',
    kanji: '辞書',
    answer: 'dictionary',
    wrongAnswers: ['book', 'magazine', 'newspaper'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'ざっし',
    kanji: '雑誌',
    answer: 'magazine',
    wrongAnswers: ['book', 'dictionary', 'newspaper'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'しんぶん',
    kanji: '新聞',
    answer: 'newspaper',
    wrongAnswers: ['book', 'dictionary', 'magazine'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'ノート',
    kanji: '',
    answer: 'notebook',
    wrongAnswers: ['personal organiser', 'business card', '(credit) card'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'てちょう',
    kanji: '手帳',
    answer: 'personal organiser',
    wrongAnswers: ['notebook', 'business card', '(credit) card'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'めいし',
    kanji: '名刺',
    answer: 'business card',
    wrongAnswers: ['notebook', 'personal organiser', '(credit) card'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'カード',
    kanji: '',
    answer: '(credit) card',
    wrongAnswers: ['notebook', 'personal organiser', 'business card'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'えんぴつ',
    kanji: '鉛筆',
    answer: 'pencil',
    wrongAnswers: ['mechanical pencil', 'ballpoint pen', 'key'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'ボールペン',
    kanji: '',
    answer: 'ballpoint pen',
    wrongAnswers: ['mechanical pencil', 'pencil', 'key'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'シャープペンシル',
    kanji: '',
    answer: 'mechanical pencil, propelling pencil',
    wrongAnswers: ['pencil', 'ballpoint pen', 'key'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'かぎ',
    kanji: '',
    answer: 'key',
    wrongAnswers: ['umbrella', 'bag, briefcase', 'car, vehicle'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'とけい',
    kanji: '時計',
    answer: 'watch, clock',
    wrongAnswers: ['umbrella', 'bag, briefcase', 'car, vehicle'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'かさ',
    kanji: '傘',
    answer: 'umbrella',
    wrongAnswers: ['watch, clock', 'bag, briefcase', 'car, vehicle'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'かばん',
    kanji: '',
    answer: 'bag, briefcase',
    wrongAnswers: ['watch, clock', 'umbrella', 'car, vehicle'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'CD',
    kanji: '',
    answer: 'CD, compact disc',
    wrongAnswers: ['television', 'radio', 'camera'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'この',
    kanji: '',
    answer: 'this ～, this ～ here',
    wrongAnswers: [
      'that ～, that ～ near the listener',
      'that ～, that ～ over there',
      'these ～, these ～ here',
    ],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'その',
    kanji: '',
    answer: 'that ～, that ～ near the listener',
    wrongAnswers: [
      'this ～, this ～ here',
      'that ～, that ～ over there',
      'these ～, these ～ here',
    ],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'あの',
    kanji: '',
    answer: 'that ～, that ～ over there',
    wrongAnswers: [
      'this ～, this ～ here',
      'that ～, that ～ near the listener',
      'these ～, these ～ here',
    ],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'ほん',
    kanji: '本',
    answer: 'book',
    wrongAnswers: ['dictionary', 'magazine', 'newspaper'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'じしょ',
    kanji: '辞書',
    answer: 'dictionary',
    wrongAnswers: ['book', 'magazine', 'newspaper'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'ざっし',
    kanji: '雑誌',
    answer: 'magazine',
    wrongAnswers: ['book', 'dictionary', 'newspaper'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'しんぶん',
    kanji: '新聞',
    answer: 'newspaper',
    wrongAnswers: ['book', 'dictionary', 'magazine'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'ノート',
    kanji: '',
    answer: 'notebook',
    wrongAnswers: ['personal organiser', 'business card', '(credit) card'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'てちょう',
    kanji: '手帳',
    answer: 'personal organiser',
    wrongAnswers: ['notebook', 'business card', '(credit) card'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'めいし',
    kanji: '名刺',
    answer: 'business card',
    wrongAnswers: ['notebook', 'personal organiser', '(credit) card'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'カード',
    kanji: '',
    answer: '(credit) card',
    wrongAnswers: ['notebook', 'personal organiser', 'business card'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'ボールペン',
    kanji: '',
    answer: 'ballpoint pen',
    wrongAnswers: ['mechanical pencil', 'pencil', 'key'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'シャープペンシル',
    kanji: '',
    answer: 'mechanical pencil, propelling pencil',
    wrongAnswers: ['pencil', 'ballpoint pen', 'key'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'テレビ',
    kanji: '',
    answer: 'television',
    wrongAnswers: ['CD, compact disc', 'radio', 'camera'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'ラジオ',
    kanji: '',
    answer: 'radio',
    wrongAnswers: ['CD, compact disc', 'television', 'camera'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'カメラ',
    kanji: '',
    answer: 'camera',
    wrongAnswers: ['CD, compact disc', 'television', 'radio'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'コンピューター',
    kanji: '',
    answer: 'computer',
    wrongAnswers: ['CD, compact disc', 'television', 'radio'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'くるま',
    kanji: '車',
    answer: 'car, vehicle',
    wrongAnswers: ['umbrella', 'bag, briefcase', 'watch, clock'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'つくえ',
    kanji: '机',
    answer: 'desk',
    wrongAnswers: ['chair', 'computer', 'umbrella'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'いす',
    kanji: '',
    answer: 'chair',
    wrongAnswers: ['desk', 'computer', 'umbrella'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'チョコレート',
    kanji: '',
    answer: 'chocolate',
    wrongAnswers: ['coffee', 'souvenir, present', 'the English language'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'コーヒー',
    kanji: '',
    answer: 'coffee',
    wrongAnswers: ['chocolate', 'souvenir, present', 'the English language'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: '［お］みやげ',
    kanji: '［お］土産',
    answer: 'souvenir, present',
    wrongAnswers: ['chocolate', 'coffee', 'the English language'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'えいご',
    kanji: '英語',
    answer: 'the English language',
    wrongAnswers: ['chocolate', 'coffee', 'souvenir, present'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'にほんご',
    kanji: '日本語',
    answer: 'the Japanese language',
    wrongAnswers: ['the English language', 'souvenir, present', 'chocolate'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: '～ご',
    kanji: '～語',
    answer: '～language',
    wrongAnswers: ['the Japanese language', 'souvenir, present', 'chocolate'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'なん',
    kanji: '何',
    answer: 'what',
    wrongAnswers: ['how', 'when', 'where'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'そう',
    kanji: '',
    answer: 'so',
    wrongAnswers: ['yes', 'no', 'maybe'],
    topic: 'Words',
    lesson: '2 Words',
  },
  {
    word: 'ここ',
    kanji: '',
    answer: 'here, this place',
    wrongAnswers: [
      'there, that place near the listener',
      'that place over there',
      'where, what place',
    ],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'そこ',
    kanji: '',
    answer: 'there, that place near the listener',
    wrongAnswers: ['here, this place', 'that place over there', 'where, what place'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'あそこ',
    kanji: '',
    answer: 'that place over there',
    wrongAnswers: ['here, this place', 'there, that place near the listener', 'where, what place'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'どこ',
    kanji: '',
    answer: 'where, what place',
    wrongAnswers: [
      'here, this place',
      'there, that place near the listener',
      'that place over there',
    ],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'きょうしつ',
    kanji: '教室',
    answer: 'classroom',
    wrongAnswers: ['dining hall, canteen', 'office', 'conference room, meeting room'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'しょくどう',
    kanji: '食堂',
    answer: 'dining hall, canteen',
    wrongAnswers: ['classroom', 'office', 'conference room, meeting room'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'じむしょ',
    kanji: '事務所',
    answer: 'office',
    wrongAnswers: ['classroom', 'dining hall, canteen', 'conference room, meeting room'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'かいぎしつ',
    kanji: '会議室',
    answer: 'conference room, meeting room',
    wrongAnswers: ['classroom', 'dining hall, canteen', 'office'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'うけつけ',
    kanji: '受付',
    answer: 'reception desk',
    wrongAnswers: ['lobby', 'room', 'toilet, rest room'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'ロビー',
    kanji: '',
    answer: 'lobby',
    wrongAnswers: ['reception desk', 'room', 'toilet, rest room'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'へや',
    kanji: '部屋',
    answer: 'room',
    wrongAnswers: ['reception desk', 'lobby', 'toilet, rest room'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'トイレ （おてあらい）',
    kanji: '(お手洗い）',
    answer: 'toilet, rest room',
    wrongAnswers: ['reception desk', 'lobby', 'room'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'かいだん',
    kanji: '階段',
    answer: 'staircase',
    wrongAnswers: ['lift, elevator', 'escalator', 'vending machine'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'エレベーター',
    kanji: '',
    answer: 'lift, elevator',
    wrongAnswers: ['staircase', 'escalator', 'vending machine'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'エスカレーター',
    kanji: '',
    answer: 'escalator',
    wrongAnswers: ['staircase', 'lift, elevator', 'vending machine'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'じどうはんばいき',
    kanji: '自動販売機',
    answer: 'vending machine',
    wrongAnswers: ['staircase', 'lift, elevator', 'escalator'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'でんわ',
    kanji: '電話',
    answer: 'telephone handset, telephone call',
    wrongAnswers: ['vending machine', 'lift, elevator', 'escalator'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: '［お］くに',
    kanji: '［お］国',
    answer: 'country',
    wrongAnswers: ['company', 'house, home', 'department, counter'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'かいしゃ',
    kanji: '会社',
    answer: 'company',
    wrongAnswers: ['country', 'house, home', 'department, counter'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'うち',
    kanji: '',
    answer: 'house, home',
    wrongAnswers: ['country', 'company', 'department, counter'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'くつ',
    kanji: '靴',
    answer: 'shoes',
    wrongAnswers: ['tie, necktie', 'wine', 'department, counter'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'ネクタイ',
    kanji: '',
    answer: 'tie, necktie',
    wrongAnswers: ['shoes', 'wine', 'department, counter'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'ワイン',
    kanji: '',
    answer: 'wine',
    wrongAnswers: ['shoes', 'tie, necktie', 'department, counter'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'うりば',
    kanji: '売り場',
    answer: 'department, counter',
    wrongAnswers: ['shoes', 'tie, necktie', 'wine'],
    topic: 'Words',
    lesson: '3 Words',
  },
  {
    word: 'いくら',
    kanji: '',
    answer: 'how much',
    wrongAnswers: ['hundred', 'thousand', 'ten thousand'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'ひゃく',
    kanji: '百',
    answer: 'hundred',
    wrongAnswers: ['how much', 'thousand', 'ten thousand'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'せん',
    kanji: '千',
    answer: 'thousand',
    wrongAnswers: ['how much', 'hundred', 'ten thousand'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'まん',
    kanji: '万',
    answer: 'ten thousand',
    wrongAnswers: ['how much', 'hundred', 'thousand'],
    topic: 'Numbers',
    lesson: '0',
  },
  {
    word: 'おきます',
    kanji: '起きます',
    answer: 'get up, wake up',
    wrongAnswers: ['sleep, go to bed', 'work', 'take a rest, take a holiday'],
    topic: 'Words',
    lesson: '4 Words',
  },
  {
    word: 'ねます',
    kanji: '寝ます',
    answer: 'sleep, go to bed',
    wrongAnswers: ['get up, wake up', 'work', 'take a rest, take a holiday'],
    topic: 'Words',
    lesson: '4 Words',
  },
  {
    word: 'はたらきます',
    kanji: '働きます',
    answer: 'work',
    wrongAnswers: ['get up, wake up', 'sleep, go to bed', 'take a rest, take a holiday'],
    topic: 'Words',
    lesson: '4 Words',
  },
  {
    word: 'やすみます',
    kanji: '休みます',
    answer: 'take a rest, take a holiday',
    wrongAnswers: ['get up, wake up', 'sleep, go to bed', 'work'],
    topic: 'Words',
    lesson: '4 Words',
  },
  {
    word: 'おわります',
    kanji: '終わります',
    answer: 'finish',
    wrongAnswers: ['get up, wake up', 'sleep, go to bed', 'work'],
    topic: 'Words',
    lesson: '4 Words',
  },
  {
    word: 'デパート',
    kanji: '',
    answer: 'department store',
    wrongAnswers: ['bank', 'post office', 'library'],
    topic: 'Words',
    lesson: '4 Words',
  },
  {
    word: 'ぎんこう',
    kanji: '銀行',
    answer: 'bank',
    wrongAnswers: ['department store', 'post office', 'library'],
    topic: 'Words',
    lesson: '4 Words',
  },
  {
    word: 'ゆうびんきょく',
    kanji: '郵便局',
    answer: 'post office',
    wrongAnswers: ['department store', 'bank', 'library'],
    topic: 'Words',
    lesson: '4 Words',
  },
  {
    word: 'としょかん',
    kanji: '図書館',
    answer: 'library',
    wrongAnswers: ['department store', 'bank', 'post office'],
    topic: 'Words',
    lesson: '4 Words',
  },
  {
    word: 'いま',
    kanji: '今',
    answer: 'now',
    wrongAnswers: ["o'clock", 'minute', 'half'],
    topic: 'Words',
    lesson: '4 Words',
  },
  {
    word: 'はじめまして',
    kanji: '初めまして。',
    answer: 'How do you do?',
    wrongAnswers: ['I’m from ～（country）.', 'Pleased to meet you.', 'Excuse me, but'],
    topic: 'Phrases',
    lesson: '1 Phrases',
  },
  {
    word: '～から きました。',
    kanji: '～から 来ました。',
    answer: 'I’m from ～（country）.',
    wrongAnswers: ['How do you do?', 'Pleased to meet you.', 'May I have your name?'],
    topic: 'Phrases',
    lesson: '1 Phrases',
  },
  {
    word: '［どうぞ］よろしく［おねがいします］',
    kanji: '[どうぞ] よろしく [お願いします]',
    answer: 'Pleased to meet you.',
    wrongAnswers: ['How do you do?', 'I’m from ～（country）.', 'May I have your name?'],
    topic: 'Phrases',
    lesson: '1 Phrases',
  },
  {
    word: 'しつれいですが',
    kanji: '失礼ですが',
    answer: 'Excuse me, but',
    wrongAnswers: ['How do you do?', 'I’m from ～（country）.', 'May I have your name?'],
    topic: 'Phrases',
    lesson: '1 Phrases',
  },
  {
    word: 'おなまえは?',
    kanji: 'お名前は？',
    answer: 'May I have your name?',
    wrongAnswers: ['How do you do?', 'I’m from ～（country）.', 'Pleased to meet you.'],
    topic: 'Phrases',
    lesson: '1 Phrases',
  },
  {
    word: 'こちらは ～さんです。',
    kanji: '',
    answer: 'This is Mr./Ms. ～.',
    wrongAnswers: ['How do you do?', 'I’m from ～（country）.', 'May I have your name?'],
    topic: 'Phrases',
    lesson: '1 Phrases',
  },
  {
    word: 'あのう',
    kanji: '',
    answer: 'Er...',
    wrongAnswers: ['Oh? What!', 'Here you are.', 'Thank you [very much].'],
    topic: 'Phrases',
    lesson: '2 Phrases',
  },
  {
    word: 'えっ',
    kanji: '',
    answer: 'Oh? What!',
    wrongAnswers: ['Er...', 'Here you are.', 'Thank you [very much].'],
    topic: 'Phrases',
    lesson: '2 Phrases',
  },
  {
    word: 'どうぞ。',
    kanji: '',
    answer: 'Here you are.',
    wrongAnswers: ['Er...', 'Oh? What!', 'Thank you [very much].'],
    topic: 'Phrases',
    lesson: '2 Phrases',
  },
  {
    word: '［どうも］ありがとう ［ございます］',
    kanji: '',
    answer: 'Thank you [very much].',
    wrongAnswers: ['Er...', 'Oh? What!', 'Here you are.'],
    topic: 'Phrases',
    lesson: '2 Phrases',
  },
  {
    word: 'そうですか。',
    kanji: '',
    answer: 'I see.',
    wrongAnswers: ['Er...', 'Oh? What!', 'Here you are.'],
    topic: 'Phrases',
    lesson: '2 Phrases',
  },
  {
    word: 'ちがいます',
    kanji: '違います',
    answer: "No, it isn't./You are wrong.",
    wrongAnswers: ['Er...', 'Oh? What!', 'Here you are.'],
    topic: 'Phrases',
    lesson: '2 Phrases',
  },
  {
    word: 'あ',
    kanji: '',
    answer: 'Oh!',
    wrongAnswers: ['Er...', 'Oh? What!', 'Here you are.'],
    topic: 'Phrases',
    lesson: '2 Phrases',
  },
  {
    word: 'これから おせわに なります。',
    kanji: 'これから お世話に なります。',
    answer: 'Thank you in advance for your kindness.',
    wrongAnswers: ['Er...', 'Oh? What!', 'Here you are.'],
    topic: 'Phrases',
    lesson: '2 Phrases',
  },
  {
    word: 'こちらこそ［どうぞ］ よろしく［おねがいします］。',
    kanji: 'こちらこそ［どうぞ］ よろしく [お願いします］。',
    answer: 'Pleased to meet you, too.',
    wrongAnswers: ['Er...', 'Oh? What!', 'Here you are.'],
    topic: 'Phrases',
    lesson: '2 Phrases',
  },
  {
    word: 'すみません。',
    kanji: '',
    answer: 'Excuse me.',
    wrongAnswers: ['Thanks.', 'Welcome./May I help you?', 'Please show me [～].'],
    topic: 'Phrases',
    lesson: '3 Phrases',
  },
  {
    word: 'どうも。',
    kanji: '',
    answer: 'Thanks.',
    wrongAnswers: ['Excuse me.', 'Welcome./May I help you?', 'Please show me [～].'],
    topic: 'Phrases',
    lesson: '3 Phrases',
  },
  {
    word: 'いらっしゃいませ。',
    kanji: '',
    answer: 'Welcome./May I help you?',
    wrongAnswers: ['Excuse me.', 'Thanks.', 'Please show me [～].'],
    topic: 'Phrases',
    lesson: '3 Phrases',
  },
  {
    word: '[～を］ みせて ください。',
    kanji: '',
    answer: 'Please show me [～].',
    wrongAnswers: ['Excuse me.', 'Thanks.', 'Welcome./May I help you?'],
    topic: 'Phrases',
    lesson: '3 Phrases',
  },
  {
    word: 'じゃ',
    kanji: '',
    answer: 'well, then, in that case',
    wrongAnswers: ['Excuse me.', 'Thanks.', 'Welcome./May I help you?'],
    topic: 'Phrases',
    lesson: '3 Phrases',
  },
  {
    word: '[～を］ください。',
    kanji: '',
    answer: 'Give me [～], please.',
    wrongAnswers: ['Excuse me.', 'Thanks.', 'Welcome./May I help you?'],
    topic: 'Phrases',
    lesson: '3 Phrases',
  },
];
